### PR TITLE
Fix reference and value types

### LINKED ISSUE #158: Fix the reference / value_types
Check all containers. 

Make sure that 
1. it has a test and
2. the types are correct

Make sure that each of the 8 containers has a test that ensures the value_type lifetime extends beyond the container's lifetime.

### PR DESCRIPTION
**Pull request by alandefreitas**
Fix #158

This PR implements the following changes in container types:

- `segments_encoded_view`
    - `reference` = `string_view`
    - `value_type` = `string_view` -> Replace with `const_string`
- `segments_encoded`
    - `reference` = `string_view`
    - `value_type` = `std::string` -> Replace with `const_string`
- `segments_view`
    - `reference` = `const_string`
    - `value_type` = `const_string`
- `segments`
    - `reference` = `const_string`
    - `value_type` = `const_string`
- `params_encoded_view`
    - `reference` = `query_param_view`(`string_view`)
    - `value_type` = `query_param` (`std::string`) -> Replace with `query_param` (`const_string`)
- `params_encoded`
    - `reference` = `query_param_view`(`string_view`)
    - `value_type` = `query_param_view`(`string_view`) -> Replace with `query_param` (`const_string`)
- `params_view`
    - `reference` = `params_view::value_type`(`const_string`) -> Replace with `query_param` (`const_string`)
    - `value_type` = `params_view::value_type`(`const_string`) -> Replace with `query_param` (`const_string`)
- `params`
    - `reference` = `params::reference`(`const_string`) -> Replace with `query_param` (`const_string`)
    - `value_type` = `params::reference`(`const_string`) -> Replace with `query_param` (`const_string`)

### CODE REVIEW

File: include/boost/url/impl/const_string.hpp [hunk 1]
```diff
@@ -172,9 +172,10 @@ const_string(
     string_view s,
     Allocator const& a)
 {
-    // VFALCO Should we do something special when n==0?
     if (is_small(s.size()))
     {
+        if (s.empty())
+            s = "";
         std::memcpy(data_.buf_,
```
Comment (vinniefalco) [inline include/boost/url/impl/const_string.hpp:179]: `else`?

File: include/boost/url/impl/const_string.ipp [hunk 2]
```diff
@@ -110,6 +110,8 @@ const_string::
 factory::
 operator()(string_view s) const
 {
+    if (s.empty())
+        s = "";
```
Comment (vinniefalco) [inline include/boost/url/impl/const_string.ipp:114]: wait, what is this?

File: include/boost/url/impl/const_string.hpp [hunk 3]
```diff
@@ -172,9 +172,10 @@ const_string(
     string_view s,
     Allocator const& a)
 {
-    // VFALCO Should we do something special when n==0?
     if (is_small(s.size()))
     {
+        if (s.empty())
+            s = "";
```
Comment (vinniefalco) [inline include/boost/url/impl/const_string.hpp:178]: why do this?

why not `s = {};`?

File: include/boost/url/detail/parts_base.hpp [hunk 4]
```diff
@@ -11,6 +11,7 @@
 #define BOOST_URL_DETAIL_PARTS_BASE_HPP
 
 #include <boost/url/error.hpp>
+#include <boost/url/string_view.hpp>
```
Comment (vinniefalco) [inline include/boost/url/detail/parts_base.hpp:14]: What's this for? The file doesn't use `string_view`

File: include/boost/url/impl/params.hpp [hunk 5]
```diff
@@ -249,7 +250,7 @@ inline
 void
 params::
 assign(std::initializer_list<
-    value_type> init)
+    query_param_view> init)
```
Comment (vinniefalco) [inline include/boost/url/impl/params.hpp:253]: but this should say `reference` not `query_param_view`

File: include/boost/url/impl/params.hpp [hunk 6]
```diff
@@ -386,7 +387,7 @@ auto
 params::
 insert(
     iterator before,
-    value_type const& v) ->
+    query_param_view const& v) ->
```
Comment (vinniefalco) [inline include/boost/url/impl/params.hpp:390]: I think this needs to say `reference`, but I could be convinced otherwise

File: include/boost/url/impl/params_encoded.hpp [hunk 7]
```diff
@@ -230,7 +231,7 @@ inline
 params_encoded&
 params_encoded::
 operator=(std::initializer_list<
-    value_type> init)
+    reference> init)
```
Comment (vinniefalco) [inline include/boost/url/impl/params_encoded.hpp:234]: See this makes sense, `reference`

File: include/boost/url/impl/const_string.ipp (hunk 2 above)
Comment (alandefreitas) [reply include/boost/url/impl/const_string.ipp:114]: We need to check if `s.empty()` (but we don't need the `s = "";`) because `s.data()` might be `nullptr` for an empty string. I'll push the changes when you're done reviewing.

File: include/boost/url/impl/params_encoded.ipp [hunk 8]
```diff
@@ -22,20 +22,20 @@ auto
...
 operator[](
     std::size_t pos) const ->
-        value_type
+        reference
 {
     BOOST_ASSERT(pos < u_->nparam_);
     auto const r = u_->param(pos);
     if(r.nv > 0)
-        return value_type{
+        return reference{
```
Comment (vinniefalco) [inline include/boost/url/impl/params_encoded.ipp:30]: you could leave out the word `reference` and just return an init-list

File: include/boost/url/impl/params_view.ipp [hunk 9]
```diff
@@ -18,70 +18,6 @@
 namespace boost {
 namespace urls {
 
-params_view::
-value_type::
-~value_type() noexcept = default;
```
Comment (vinniefalco) [inline include/boost/url/impl/params_view.ipp:23]: The purpose of emitting these definitions in the DLL is to avoid having them emitted in the user's code

File: include/boost/url/impl/const_string.hpp (hunk 3 above)
Comment (alandefreitas) [reply include/boost/url/impl/const_string.hpp:178]: `s = {}` was what caused the problem in the first place. `s.p_` becomes `nullptr`. Anyway, we don't need this line anymore.

```cpp
BOOST_CONSTEXPR basic_string_view() BOOST_NOEXCEPT: p_(), n_()
    {
    }
```

File: include/boost/url/params_view.hpp [hunk 10]
```diff
@@ -12,8 +12,9 @@
 #define BOOST_URL_PARAMS_VIEW_HPP
 
 #include <boost/url/detail/config.hpp>
-#include <boost/url/const_string.hpp>
 #include <boost/url/detail/parts_base.hpp>
+#include <boost/url/const_string.hpp>
```
Comment (vinniefalco) [inline include/boost/url/params_view.hpp:16]: const_string.hpp is not needed?

File: include/boost/url/detail/parts_base.hpp (hunk 4 above)
Comment (alandefreitas) [reply include/boost/url/detail/parts_base.hpp:14]: `pos_t` is defined in `boost/url/string_view.hpp`

File: include/boost/url/impl/params_view.ipp (hunk 9 above)
Comment (alandefreitas) [reply include/boost/url/impl/params_view.ipp:23]: Sorry. What does that have to do with removing `params_view::value_type::...`?

File: include/boost/url/detail/parts_base.hpp (hunk 4 above)
Comment (vinniefalco) [reply include/boost/url/detail/parts_base.hpp:14]: maybe that should go in config.hpp? do we have both `pos_t` and `off_t`? We only need one.

File: include/boost/url/impl/const_string.ipp [hunk 11]
```diff
@@ -115,10 +115,11 @@ operator()(string_view s) const
...
             char* dest)
         {
-            std::memcpy(
-                dest,
-                s.data(),
-                s.size());
+            if (!s.empty())
+                std::memcpy(
+                    dest,
+                    s.data(),
```
Comment (vinniefalco) [inline include/boost/url/impl/const_string.ipp:121]: oh yeah, `nullptr` is UB even if `size()==0)`...

File: include/boost/url/impl/params_view.ipp (hunk 9 above)
Comment (vinniefalco) [reply include/boost/url/impl/params_view.ipp:23]: I'm saying that whatever replaces this type, should emit semi-expensive special member definitions in the DLL and not the user's binary.

File: include/boost/url/query_param.hpp [hunk 12]
```diff
@@ -115,16 +117,49 @@ struct query_param
...
             v.value :
-            string_view())
+            string_view(), a)
         , has_value(v.has_value)
     {
     }
 
+    /** Constructor
+    */
+    template <class Allocator = std::allocator<char>>
```
Comment (vinniefalco) [inline include/boost/url/query_param.hpp:138]: huh.. This template parameter is not used

File: include/boost/url/query_param.hpp [hunk 13]
```diff
@@ -115,16 +117,49 @@ struct query_param
...
+        bool has_value_)
+        : key(key_)
+        , value(value_)
+        , has_value(has_value_)
+    {
+    }
+
+    /** Constructor
+    */
+    template <class Allocator = std::allocator<char>>
```
Comment (vinniefalco) [inline include/boost/url/query_param.hpp:151]: I think this overload should accept `const_string::factory const&` instead of `Allocator const&`, we don't need a separate _Allocator_ overload. That's actually a pessimization since we will be constructing two different factories for the same allocator (one for the key and one for the value).

File: include/boost/url/query_param.hpp [hunk 14]
```diff
@@ -136,17 +171,29 @@ struct query_param
...
     }
 #endif
 #endif
+
+private:
+    friend class params_view;
+    friend class params;
+
+    BOOST_URL_DECL
+    query_param(
```
Comment (vinniefalco) [inline include/boost/url/query_param.hpp:192]: yeah shouldn't we just make this public?

Comment (alandefreitas) [reply include/boost/url/query_param.hpp:192]: This overload

```
query_param(
        char const* s,
        std::size_t nk,
        std::size_t nv,
        const_string::factory const& a);
```

has no meaning to users. It's used by the params constructors to create query_param from a `raw_param`, which is an implementation detail.

In the future, we could have some overload like:

```
query_param(
        string_view k,
        string_view v,
        bool has_value,
        const_string::factory const& a);
```

but there's no demand for that in the library or from users yet.

File: include/boost/url/detail/config.hpp [hunk 15]
```diff
@@ -84,4 +86,9 @@
 # error Unknown or unsupported architecture, please open an issue
 #endif
 
+#ifndef BOOST_URL_DOCS
+// this is private
```
Comment (vinniefalco) [inline include/boost/url/detail/config.hpp:90]: self-explanatory, since it is in detail/config.hpp (and also protected with the macro)

File: include/boost/url/detail/config.hpp [hunk 16]
```diff
@@ -13,6 +14,7 @@
 #include <boost/config.hpp>
 #include <boost/config/workaround.hpp>
 #include <limits.h>
+#include <stddef.h>
```
Comment (vinniefalco) [inline include/boost/url/detail/config.hpp:17]: but can we avoid including another header?

File: include/boost/url/detail/config.hpp [hunk 17]
```diff
@@ -84,4 +86,9 @@
 # error Unknown or unsupported architecture, please open an issue
 #endif
 
+#ifndef BOOST_URL_DOCS
+// this is private
+using pos_t = size_t;
+#endif
```
Comment (vinniefalco) [inline include/boost/url/detail/config.hpp:92]: This could end up being a different size depending on platform, no? Why can't we do `unsigned int`? or uhh some guaranteed 32-bit integer type?

File: include/boost/url/detail/parts_base.hpp [hunk 18]
```diff
@@ -10,6 +10,7 @@
 #ifndef BOOST_URL_DETAIL_PARTS_BASE_HPP
 #define BOOST_URL_DETAIL_PARTS_BASE_HPP
 
+#include <boost/url/detail/config.hpp>
```
Comment (vinniefalco) [inline include/boost/url/detail/parts_base.hpp:13]: detail files don't need to include config.hpp... you only need to include config.hpp as the first include of a public header
