### PR TITLE
missing url javadoc

### LINKED ISSUE #174: Missing javadoc in set_userinfo
https://master.url.cpp.al/url/ref/boost__urls__url/set_userinfo.html

### LINKED ISSUE #175: Incorrectly formatted See-Also section
https://master.url.cpp.al/url/ref/boost__urls__url/host.html

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #174, fix #175

### CODE REVIEW

File: include/boost/url/url.hpp [hunk 1]
```diff
@@ -1062,21 +1085,85 @@ class BOOST_SYMBOL_VISIBLE url
...
+
+        @par Specification
+        @li <a href="https://datatracker.ietf.org/doc/html/rfc3986#section-3.3"
+            >3.3. Path (rfc3986)</a>
+    */
     template<class Allocator =
         std::allocator<char>>
     urls::segments
-    segments(Allocator const& a = {}) noexcept
+    segments(Allocator const& alloc = {}) noexcept
```
Comment (vinniefalco) [inline include/boost/url/url.hpp:1164]: `alloc` is undocumented

**Comment by vinniefalco** [comment]
LGTM but the commit message should read "add missing url member javadocs"
